# Archivo de credenciales OADS
# Guarda este archivo como 'oads_credentials.toml' en el mismo directorio

[credentials]
username = "Jorgemr1998@ugr.es"
password = "26!KekW1998"

[settings]
max_retries = 3
time_tolerance_minutes = 11